#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : python-tappy
Version  : 1.8
Release  : 8
URL      : https://pypi.python.org/packages/source/t/tap.py/tap.py-1.8.tar.gz
Source0  : https://pypi.python.org/packages/source/t/tap.py/tap.py-1.8.tar.gz
Summary  : Test Anything Protocol (TAP) tools
Group    : Development/Tools
License  : BSD-2-Clause
Requires: python-tappy-bin
Requires: python-tappy-python
Requires: Pygments
Requires: argparse
Requires: nose
Requires: py
Requires: pytest
BuildRequires : Babel-python
BuildRequires : Pygments
BuildRequires : funcsigs-python
BuildRequires : nose-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : py-python
BuildRequires : pytest-python
BuildRequires : python-dev
BuildRequires : python-mock-python
BuildRequires : python3-dev
BuildRequires : pytz-python
BuildRequires : setuptools
BuildRequires : six
BuildRequires : six-python

%description
tappy
=====
[![PyPI version][pypishield]](https://pypi.python.org/pypi/tap.py)
[![BSD license][license]](https://raw.githubusercontent.com/mblayman/tappy/master/LICENSE)
[![Downloads][shield]](https://pypi.python.org/pypi/tap.py)
Linux: [![Linux status][travis]](https://travis-ci.org/mblayman/tappy)
Windows: [![Windows status][appveyor]](https://ci.appveyor.com/project/mblayman/tappy)
[![Coverage][coverage]](https://codecov.io/github/mblayman/tappy)

%package bin
Summary: bin components for the python-tappy package.
Group: Binaries

%description bin
bin components for the python-tappy package.


%package python
Summary: python components for the python-tappy package.
Group: Default

%description python
python components for the python-tappy package.


%prep
%setup -q -n tap.py-1.8

%build
export LANG=C
export SOURCE_DATE_EPOCH=1489435943
python2 setup.py build -b py2
python3 setup.py build -b py3

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
PYTHONPATH=%{buildroot}/usr/lib/python2.7/site-packages python2 setup.py test
%install
export SOURCE_DATE_EPOCH=1489435943
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/tap
/usr/bin/tappy

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
